### ISSUE TITLE
[FIX] Stattering at the beginning of match

### ISSUE THREAD

**Issue by VladWinner** [h1-mod/h1-mod#102]
(not bug report, just for pinning)
If you experience lags for the first seconds from start of playing on a new map, then open the console and enter:
`r_preloadshaders 1`
This slows down map loading a bit, but eliminates framerate stattering.
I have this setting reset after each launching client, so I recommend repeating the action when you run the executable file again.

**Comment by xXsleepy76Xx** [comment]
Thank you! I think this was the fix I was hoping for!
Originally had COD4 and H1 on a HDD, moved it to an SSD, and started getting crazy latency spikes at the beginning of every match. Even private match. 
Moved the game back to the HDD, reinstalled H1, ran that script in the console and...
Bingo!
I'm back running sweet.
Thanks again!
: )

**Comment by khabib227** [comment]
Why not make this setting persistent?
