### ISSUE TITLE
Question about split screen

### ISSUE THREAD

**Issue by VladWinner** [h1-mod/h1-mod#104]
I found console commands related to split screen, but I couldn't activate them. 
`splitscreen "0xC3957545" is read only`
![image](https://user-images.githubusercontent.com/13555921/175822928-49fef4a3-1b24-4061-9b05-08af33ea89b6.png)
Is it possible to enable this mode (at least for closed matches) if there are 2 gamepads?

**Comment by mjkzy** [comment]
All the splitscreen stuff usually left in a game is from the console port or just older engines. Some games don't have working splitscreen usually.
