### ISSUE TITLE
[Request] Implementing missing task

### ISSUE THREAD

**Issue by jokeruarwentto** [h1-mod/h1-mod#105]
Log: ``[DW] bdUNK80: missing task '122'``
Description: Crafting from depot
![image](https://user-images.githubusercontent.com/7479947/175818089-bc0381bd-a6d9-4c11-b8db-3214436589b7.png)

Log: ``[DW] bdMarketing: missing task '4'``
Description: Buying a create from Depot menu
![image](https://user-images.githubusercontent.com/7479947/175818231-f5921278-830e-459c-87c5-a483ac44a806.png)

Why ?
Because I would like to farm these items without unlocking them all.

**Comment by mjkzy** [comment]
easier said than done, will bring this up with the devs tho

**Comment by mjkzy** [comment]
what's the address you modified for cod points?

**Comment by mjkzy** [comment]
closed as a alternative is being worked on
