### ISSUE TITLE
Issue with the tabs in the main menu

### ISSUE THREAD

**Issue by Kuramabtw** [h1-mod/h1-mod#111]
hey, I have an issue in the main menu of my game wich is : I dont have the "stats" tab and the "server list" tab. As you can see on the attached picture, the "stats" tab has disappeared and the "server list" tab has been replaced by the "find game" tab as on the official game. I don't why it happened but it happened, if you guys can help me i'll be the happiest man on earth. Wishing you a very good day :)

![image_2022-06-27_073305650](https://user-images.githubusercontent.com/108253230/175866648-cd1e86a9-822a-43c3-b7ca-21c59c083354.png)

**Comment by VladWinner** [comment]
#107

**Comment by Kuramabtw** [comment]
> #107

thanks bro it worked letsgoooooooooooooo
