### ISSUE TITLE
Infinite MW loading screen when I exit the game.

### ISSUE THREAD

**Issue by domain1231** [h1-mod/h1-mod#112]
![11](https://user-images.githubusercontent.com/85142901/175942174-98eab649-7363-4774-ab87-e3e0b3213bfc.png)

![22](https://user-images.githubusercontent.com/85142901/175942210-3967f8fb-efab-44df-b238-243ebda091b2.png)

Hello this issue happen to me afteer I updated version to 1.0.2.

Normal Game was ok but let me wirte down circumstance about reproduce issue.

1.  In private match

2. Open the console and type sv_cheats 1

3. Set bot difficulty veteran.

4. Set number of bots what you want.

5. Star the game and when loading complete, open the console and type camera_thirdperson 1

6. Enjoy the game and finish the match or leaving the match early you want.

7. Get back to private match lobby and exit the game and see the issue.

I played with sv_cheats 1 and camera_thirdperson 1 since H1_MOD V1.0 and after update 1.0.2 the issue happen.

I believe the issue definitely related with 1.0.2 update and reaaly hope h1-mod dev fix this issue.

I also attached minidump link at google dirve.

https://drive.google.com/file/d/1AcWIusB_dKrNRslegcQj744AR5JSt4zZ/view?usp=sharing

https://drive.google.com/file/d/10FyRTP3xLxYOHNnhTEgDJ2VpIg0royiI/view?usp=sharing

Thanks for reading and sorry for my bad english.

**Comment by mjkzy** [comment]
> Well, it seems deleting -memoryfix parameter in shortcut solve the issue.

yeah, -memoryfix should only be used to generate the players2 folder (which is a one time error)

**Comment by domain1231** [comment]
Thanks for reply. I will close the issue.
