### ISSUE TITLE
[Request] Unlock input from multiple gamepads

### ISSUE THREAD

**Issue by VladWinner** [h1-mod/h1-mod#114]
H1-Mod/MW:R always takes control only from XInput gamepad №1, but since the split screen mode is not available on PC, I usually play with a friend on the same screen, where each of us plays with his own gamepad. 
This solution is supported in BOCW (not sure about other alternative clients). Is it possible to allow seamless switching between gamepads (unlock input from both gamepads)?

**Comment by mjkzy** [comment]
i think the two imports that h1 has, XInputGetState and XInputSetState, handle this. 

low priority imo since PC doesn't have splitscreen support natively in the first place. will close and come back on a later date if deemed necessary
