### ISSUE TITLE
Please mirror (at least) the server files somewhere else other than P2P

### ISSUE THREAD

**Issue by sdthtp** [h1-mod/h1-mod#122]
PeerToPeering is a very dangerous activity within a lot of countries in Europe, which may result in big fines. Right now, you can use the Steam Copy to play the mod without p2p, but there is no way to download the server files, without you sharing them.

Please mirror them somewhere like in GoogleDrive, Mega.nz, Zippyshare or on a local machine.

**Comment by fedddddd** [comment]
You can obtain the server files from the normal game files, just remove every `.pak` file and singleplayer files if you have them

**Comment by mjkzy** [comment]
answered by fed
