### ISSUE TITLE
Enable offline matchmaking

### ISSUE THREAD

**Issue by joseupp** [h1-mod/h1-mod#125]
In version 1.4 of H1-mod I have the playlist modified to be able to play only against bots using the game's matchmaking but in version 1.15 it doesn't work, the game doesn't start, it keeps the message "waiting for more players" and it doesn't start the countdown does not let you vote for the next map either. you could check if this has a solution, it works very well in version 1.4 but maps and all the content of version 1.15 are missing.

![2](https://user-images.githubusercontent.com/108338623/176168300-b7c33e6e-efae-4935-8c31-edcc92152fec.png)
![1](https://user-images.githubusercontent.com/108338623/176168318-74ce8873-9b37-4837-87e2-32dd934e0f7b.png)
.

**Comment by mjkzy** [comment]
may look into this but atm, its very low priority. closing for now

**Comment by khabib227** [comment]
@joseupp how you edit the matchmaker playlist?

**Comment by VelirzX** [comment]
seriously...
