### ISSUE TITLE
[Request] Implementing HTTP get and post for Lua scripting

### ISSUE THREAD

**Issue by jokeruarwentto** [h1-mod/h1-mod#127]
It'll be good to have this kind of thing, example for Discord webhook or other things.
The same way fed has already done that through his [t6-gsc-utils](https://github.com/fedddddd/t6-gsc-utils).
Thanks.

**Comment by mjkzy** [comment]
we just got curl in the client so we can add this whenever someone has time! :)

**Comment by mjkzy** [comment]
added
