### ISSUE TITLE
Mouse acceleration bug

### ISSUE THREAD

**Issue by piee-kun** [h1-mod/h1-mod#142]
Randomly the game will use a weird kind of mouse acceleration. It is impossible to try and aim as the value seemingly keeps changing. I cannot find a way to reproduce this.
Video showcasing the error: https://streamable.com/6l1ani

**Comment by mjkzy** [comment]
im assuming this is because your game hasn't preloaded textures yet and so you'll get a bit of a laggy experience at the beginning of playing

**Comment by piee-kun** [comment]
My bad, lol pressed the wrong button

**Comment by piee-kun** [comment]
I will keep the game open on Bog for roughly 20 minutes, see if that fixes the issue, however i doubt it

**Comment by piee-kun** [comment]
No, it was not the textures not loading. Found a workaround though. Use the console command `r_elevatedPriority "1"` fixed the issue for me without the need for changing the polling rates in my mouse's settings
