### ISSUE TITLE
Forcing 100% volume for audio devices

### ISSUE THREAD

**Issue by piee-kun** [h1-mod/h1-mod#143]
When the game starts, all input devices are forced to 100% volume

**Comment by VladWinner** [comment]
https://steamcommunity.com/app/393100/discussions/0/282992646969957058/
Not H1-mod related?

**Comment by piee-kun** [comment]
Wish you were right, since I already have that option on "Do nothing"

**Comment by mjkzy** [comment]
> When the game starts, all input devices are forced to 100% volume

already a commit that fixes it, will be in next major release!
