### ISSUE TITLE
splash screen freeze

### ISSUE THREAD

**Issue by user1-4-1** [h1-mod/h1-mod#145]
bought game on steam for $25 and the game will not go past the initial splash screen. it will show it then instantly close with no error message. looked everywhere for a fix as both singleplayer and multiplayer are busted, this is on a fresh win 11 install.

**Comment by mjkzy** [comment]
https://docs.h1.gg/troubleshoot#the-launcher-splash-screen-doesnt-respond-and-eventually-closes

**Comment by user1-4-1** [comment]
the screen freeze is both with h1 mod and without, also there is no antivirus installed as it is a fresh win11 home install

**Comment by user1-4-1** [comment]
![image](https://user-images.githubusercontent.com/108511846/176988692-9e42fa9c-69e9-4584-a440-8205080f1c12.png)
and that happens too

**Comment by mjkzy** [comment]
well if it says that, then your MWR install isn't good. reinstall or verify the game files on steam/torrent

**Comment by user1-4-1** [comment]
ive done reinstalling, verifying files and everything i could find, windows store version is working, still cant play h1 and yet @mjkzy marked it completed

**Comment by user1-4-1** [comment]
i think it really is just the game itself, steam and torrent have the same
problem even after verifying files and reinstalling on other drives,
meanwhile the windows store version is fine.
