### ISSUE TITLE
when i installed h1 the only thing i can play is sp and i cant play mp

### ISSUE THREAD

**Issue by joshu3r** [h1-mod/h1-mod#148]
![Desktop Screenshot 2022 07 01 - 17 42 17 32](https://user-images.githubusercontent.com/108521829/176870098-24ffe1cd-b8db-4e9a-bd97-a6b4dff2d2ed.png)
![Desktop Screenshot 2022 07 01 - 17 29 03 46](https://user-images.githubusercontent.com/108521829/176870106-1788832e-6d39-42cb-b01a-039b8e45d03e.png)
pls help

**Comment by skkuull** [comment]
Already resolved at H1-Mod's discord.
