### ISSUE TITLE
Bot's aim is inaccurate while ADS in 3rd person camera

### ISSUE THREAD

**Issue by domain1231** [h1-mod/h1-mod#151]
![11](https://user-images.githubusercontent.com/85142901/176988242-1bf720e3-9bb5-420c-9893-3b5bdbf9a405.png)
![22](https://user-images.githubusercontent.com/85142901/176988246-712ac53f-c8db-4fa7-b00d-44baeb2f311e.png)

Hello, I used to play with bot in private third person mode. But today I finally noticed that Bot's aim is inaccurate while ADS in 3rd person camera.

As you can see in snap shot I captured, while ADS bot aim sideways not aim direct on my head. This happen bots with AR, LMG, SMG automatic weapon and bot with sniper aim and shot well in third person camera.

**Comment by mjkzy** [comment]
i mean, idk what you want us to do but this is because it's third person.

**Comment by domain1231** [comment]
> i mean, idk what you want us to do but this is because it's third person.

I want fix bot aim correctly in third person camera mode but if it is not possible or dev don't want to fix it, nvm.

I had same issue in iw4x bot warfare and fortunately it was fixed.

**Comment by domain1231** [comment]
> > i mean, idk what you want us to do but this is because it's third person.
> 
>First sorry for ambiguity of my post and I want fix bot aim correctly in third person camera mode but if it is not possible or dev don't want to fix it, nvm.
> 
> I had same issue in iw4x bot warfare and fortunately it was fixed.

**Comment by mjkzy** [comment]
in my honest opinion, this is something with the game that we could maybe fix but its very very low priority. this is just how the game works

**Comment by mjkzy** [comment]
closed as this isn't such a big deal imo
