### ISSUE TITLE
Xbox Controller Not Working on both Multiplayer and Singleplayer

### ISSUE THREAD

**Issue by TheLOBeast13** [h1-mod/h1-mod#152]
I used the Xbox Series X one and I just got into multiplayer that I turned the Gamepad on, but then it says it's not when I'm using the keyboard and mouse

**Comment by TheLOBeast13** [comment]
I used the Xbox Series X one and I just got into multiplayer that I turned the Gamepad on, but then it says it's not when I'm using the keyboard and mouse

**Comment by mjkzy** [comment]
are you sure this is an issue with us?

**Comment by TheLOBeast13** [comment]
Yes it is, and that’s exactly what I have right now when needed to be resolved

**Comment by TheLOBeast13** [comment]
> are you sure this is an issue with us?

Yes it is, and that’s exactly what I have right now and needed to be resolved

**Comment by VladWinner** [comment]
I have the same gamepad and I don't experience this issue either in wireless or wired mode. Make sure that Steam is not running.

**Comment by TheLOBeast13** [comment]
> I have the same gamepad and I don't experience this issue either in wireless or wired mode. Make sure that Steam is not running.

It's working for me now like yesterday I did

**Comment by mjkzy** [comment]
not much information, don't really know what we can do here. open if you give more information
