### ISSUE TITLE
server keeps crashing on startup in 2gb RAM

### ISSUE THREAD

**Issue by Zoro-6191** [h1-mod/h1-mod#154]
can it run without actually upgrading ram? I'll provide more info if needed. 

Thanks

**Comment by skkuull** [comment]
Sadly, in require to play MWR you need to have at least 8gbs of ram
more info: https://www.systemrequirementslab.com/cyri/requirements/call-of-duty-modern-warfare-remastered/14303

**Comment by Zoro-6191** [comment]
Server hosted fine on my local laptop with 2gb memory, it had Win10. I later hosted from AWS, windows server 2012 and it keeps crashing right after the popup which says the pc doesnt meet the minimum requirements. Should I try upgrading os to 2019?

**Comment by skkuull** [comment]
Maybe your vps doesn't have steam installed?, in require to play/host a server in H1-Mod you need to have steam installed.

**Comment by Zoro-6191** [comment]
Yes that was exactly it. Thanks a bunch :>

I've hosted my server in Mumbai, India location, named [v.F], check it out :)
