### ISSUE TITLE
Dedicated Server Spawn Bots

### ISSUE THREAD

**Issue by GamingLxg** [h1-mod/h1-mod#155]
Hello,

There is no tutorial or anything documented of how to achieve spawning bots on a dedicated server. It's getting a little tedious having to spawn the bots through the console. 

Any help on this matter would highly appreciated.  Thank you so much in advance

-GamingLxg

**Comment by mjkzy** [comment]
you can use [the bot manager](https://github.com/momo5502/s1x-server-scripts/blob/main/bot-manager/__init__.lua) and change the kick function to `kickclient`
