### ISSUE TITLE
Fix laggy final killcams

### ISSUE THREAD

**Issue by mjkzy** [h1-mod/h1-mod#158]
its something related to the timescale going down and the clients just skipping a fuckton of frames in between. i've heard people like Matrix fixing this on clients, however, idk what the fix actually is.

**Comment by VladWinner** [comment]
I can't reproduce this in H1-Mod, although I've seen this before in a third-party MW2 clients.

**Comment by mjkzy** [comment]
not important really. will come back to it if it is
