### ISSUE TITLE
Servers keep lagging and stuttering on choosing loadout after loading screen

### ISSUE THREAD

**Issue by TheLOBeast13** [h1-mod/h1-mod#165]
I have 1650 Ti that's causing the performance by running the match of beginning and what has already started from.

**Comment by mjkzy** [comment]
using `/r_preloadshaders 1` in console will preload the shaders before each map but will have longer load times. the performance hitch is the game still processing the map's shaders.

**Comment by khabib227** [comment]
Why not make this setting persistent?
