### ISSUE TITLE
Campaign causes stuttering and lagging while OBS is on screen with and without recording

### ISSUE THREAD

**Issue by TheLOBeast13** [h1-mod/h1-mod#174]
So in gameplay footage, it usually works with fullscreen windowed mode that doesn’t have black screen on OBS while fullscreen mode that does have black screen like I can’t even adjust a better FPS to make the game go running smoothly if possible

**Comment by mjkzy** [comment]
try `/r_preloadshaders 1`

**Comment by TheLOBeast13** [comment]
> try `/r_preloadshaders 1`

Alright

**Comment by TheLOBeast13** [comment]
Now I did, but they take longer times than normal ones on multiplayer for performance that was getting buggy
