### ISSUE TITLE
Script are re-executed every round in round based games.

### ISSUE THREAD

**Issue by Chenterito** [h1-mod/h1-mod#175]
for example in domain, when changing round, the scripts are executed again. I have a welcome message script when connecting the player at the start of the game. But when it changes round in domain it is executed again.

**Comment by mjkzy** [comment]
this is intended behavior. gsc scripts also do this. use persistent variables or dvars to check if you should run welcome message or first round specific code

**Comment by Chenterito** [comment]
I think it shouldn't be like that. I don't know if I explain myself. They recharge each round as if it were a new map.

**Comment by mjkzy** [comment]
yes, and like I said, that is intended. the stock game's gsc also does the same and they make it so the same stuff doesn't happen when the gsc re-executes. using persistent variables are vars that don't lose its value when the game is still going on (because the GSC VM resets a bunch)
