### ISSUE TITLE
Game crash when click activate prestige

### ISSUE THREAD

**Issue by hxj662630** [h1-mod/h1-mod#180]
[https://i.ytimg.com/vi/lde9SSjd2AE/maxresdefault.jpg]
Game will crash when click the activate prestige button,
but after game restart the prestige actually work(lv55 - > prestige 1 )

**Comment by mjkzy** [comment]
do you have a crashdump?

**Comment by mjkzy** [comment]
reopen if you have more information

**Comment by hxj662630** [comment]
[h1-mod-crash-2-2022-07-12-01-28-08.zip](https://github.com/h1-mod/h1-mod/files/9169533/h1-mod-crash-2-2022-07-12-01-28-08.zip)
[h1-mod-crash-2-2022-07-12-01-28-09.zip](https://github.com/h1-mod/h1-mod/files/9169535/h1-mod-crash-2-2022-07-12-01-28-09.zip)
it's  here@[mjkzy](https://github.com/mjkzy)

**Comment by hxj662630** [comment]
> reopen if you have more information
Uploaded

**Comment by skkuull** [comment]
well, this is a known problem

**Comment by mjkzy** [comment]
seems to be demonware related. my idb claims it's "PublicProfileInfo::deserialize" both times it crashed. maybe we need to change something on our emulation?
