### ISSUE TITLE
h1-mod Crashing after black screen

### ISSUE THREAD

**Issue by Raiden40** [h1-mod/h1-mod#188]
hello....
i downloaded the game files from torrent given in the website
i downloaded the latest h1-mod from the link given in the website
uninstalled my quick heal total security... allowed the app in firewall for public and private networks, disabled windows defender also, installed steam too, upgraded the drivers and i am using win 10 original version ....

The issue is as soon as i launch the h1 mod exe... h1 mod (a green square with h1 written on it) is displayed then a black full screen window opens and it just closes in 1sec but i have noticed a small icon displays in the lower right corner but nothing happens

MY SPECS:
CPU - RYZEN 7 3750H 2.30ghz
GPU - NVIDIA GTX 1650 4gb
RAM - 8GB DDR4 2400mHz
OS - Windows 10

**Comment by skkuull** [comment]
Make sure to have at least steam installed in require to play H1-Mod.

**Comment by Raiden40** [comment]
> Make sure to have at least steam installed in require to play H1-Mod.

i already have the latest version of steam installed i also checked for update its on the latest version

**Comment by skkuull** [comment]
could you provide a screenshot of how the error looks like?

**Comment by Raiden40** [comment]
> could you provide a screenshot of how the error looks like?

sir, there is no error showing i just double click the h1mod.exe then the box with h1 mod logo appears on screen then a black full screen window opens and after that nothing happens.... it just closes

**Comment by skkuull** [comment]
good
