### ISSUE TITLE
Modern warfare remastred h1 mod launcher doesnt show options for mp or sp

### ISSUE THREAD

**Issue by LethalManBoob** [h1-mod/h1-mod#194]
Im using linux proton. base game runs fine. Its just a blank launcher.

**Comment by DeZ7ro** [comment]
same as https://github.com/h1-mod/h1-mod/issues/88#issue-1283949942

**Comment by DeZ7ro** [comment]
Im completely ignorant as to how this works but could it be possible to make it work doing the same things that plutonium and x labs do to run on linux? Or is the game itself the problem?

**Comment by skkuull** [comment]
maybe, but guaranteed not in near future.
