### ISSUE TITLE
h1 not launching

### ISSUE THREAD

**Issue by daztaw** [h1-mod/h1-mod#232]
the game has been working fine until the h1 mod promoted me to update i clicked yes tried to run the game since then it wont launch it just freezes with the mw loading screen anyone got whats causing this? also  i noticed the cmd that used to run in the background doesn't open anymore either

**Comment by mjkzy** [comment]
do you have any crash dumps

**Comment by daztaw** [comment]
> do you have any crash dumps

It was avast anti virus had to install it to fix it thanks
