### ISSUE TITLE
Campaign crashing on start of mission Bog 

### ISSUE THREAD

**Issue by MessyRaver** [h1-mod/h1-mod#244]
Hi, every time i try to load the mission 'Bog' the whole game crashes, i have tried loading it from my last save point in resume and also under mission select. It crashes on the loading story screen, it never loads the level, lading bar is 80-90% full.
im using a 3080 12gb, ryzen 5600 and 16gb of ram its not a new build and runs fine.

Any ideas?

Re install? What files do i need to save to not loose progression if i do.

Thanks

**Comment by yoyothebest** [comment]
This happens on Steam version as well. Just disable shader preloading and you should be good to go.

**Comment by MessyRaver** [comment]
Thanks!! I didn't realise that there were different graphics settings for multi and single player. I had already turned it off for multiplayer.

Sorted.
