### ISSUE TITLE
Menu options for server browser or stats not showing.

### ISSUE THREAD

**Issue by florisdipt** [h1-mod/h1-mod#282]
Probably same as #276 but more detailed.

Installed via torrent
Latest version from releases page. 
![image](https://user-images.githubusercontent.com/55819399/191102081-9daec79f-862f-4a8e-ae08-7f49f4b895fe.png)

Menu options for server browser nor stats is showing
![image](https://user-images.githubusercontent.com/55819399/191102226-8c1b6709-8db7-4bfb-9cc6-d812e1c3f21d.png)

![image](https://user-images.githubusercontent.com/55819399/191102378-00ba9e99-fba0-450e-b398-5eb2a7b2394f.png)

Windows system info:

![image](https://user-images.githubusercontent.com/55819399/191102888-1349f3d0-eccd-4f3c-8e4e-e64d09df04ac.png)

Willing to provide more info if wanted.

Looking forward to trying this mod it looks cool!

**Comment by yoyothebest** [comment]
Currently the lui files are being downloaded into the local appdata and are not supported by the latest release build. They will work on 1.0.6, but right now you need to manually install the lui files and drop them to \data\ui_scripts

**Comment by florisdipt** [comment]
Okay thanks that did the trick, for anyone else wanting to do this fix. Heres what i did:
![image](https://user-images.githubusercontent.com/55819399/191109005-f75cbd2d-6f59-4d23-ab19-a66567b96066.png)

**Comment by florisdipt** [comment]
https://github.com/h1-mod/h1-mod/pull/278

**Comment by gamingBEAST69** [comment]
i cant find a data folder what so ever, did what florisdipt did

**Comment by VladWinner** [comment]
> i cant find a data folder

`%localappdata%/h1-mod/cdata`

**Comment by fedddddd** [comment]
> Currently the lui files are being downloaded into the local appdata and are not supported by the latest release build. They will work on 1.0.6, but right now you need to manually install the lui files and drop them to \data\ui_scripts

No they are not, each branch has its own files, develop files wont be downloaded if you are on the release build.  
The issue was with the update publish script which is now fixed, run the update again and it will work.
