### ISSUE TITLE
Incomplete text appearing briefly in MP class selection & extreme lag happening at MP round start : /

### ISSUE THREAD

**Issue by xXsleepy76Xx** [h1-mod/h1-mod#319]
I've tried to uninstall/reinstall of both H1mod & Valid Steam copy of COD4-MWR multiple times to no avail. 
Any help would be most welcome. 
I was a former closed server XGC test beta for the original COD4, and I really love what this community is doing! 
Thanks in advance!
System: 
i5 3470 (soon upgrading to i7 3770)
Gigabyte GA-B75M-D3H MB
GTX 750 ti 2gb GPU
12gb "matched" ram (1 faulty RAM slot out of 4)
x1 500gb Crucial SSD internal (for OS and apps)
x1 1,000gb HDD (for backup of OS, apps, vts plugins, & storage)
x1 WD 500gb external storage
x1 500gb Kingston internal (exclusively for Steam/Origin game storage)

**Comment by skkuull** [comment]
try `r_preloadshaders 1`
