### ISSUE TITLE
V button for changing from first person to third person not working [Spectator Mode]

### ISSUE THREAD

**Issue by amrurikaj** [h1-mod/h1-mod#320]
Hi teams,

I believe this is just small bug only. V button for changing from first person to third person not working in spectator mode for both Public and Private Match.

Steps to reproduce:

1. Click private match.
2. Click game setting.
3. Go to general settings and set spectating "FREE".
4. Set spectating POV "First" or "Third Person".
5. Play and choose team as spectator.
6. Click V button.

Expected Result:
The V button should change the POV.

Actual Result:
The V button not change the POV.

![2022-10-12 18_02_15-Call of Duty®_ Modern Warfare® Remastered Multiplayer](https://user-images.githubusercontent.com/113702897/195315661-983b0a95-0669-41e6-9fb7-164bfbb66cc3.png)
![2022-10-12 18_03_20-Call of Duty®_ Modern Warfare® Remastered Multiplayer](https://user-images.githubusercontent.com/113702897/195315677-2b0da0cc-4b85-47f8-a4e9-a72a3eda9c68.png)

**Comment by mjkzy** [comment]
looking into this, i don't actually know if any former Infinity Ward games have third person spectating. this may just be a accident from the devs and there might not be any logic for this in the first place

**Comment by amrurikaj** [comment]
hi @mjkzy,

Actually the original one, they do have this function. Just check with the steam version
![2022-12-24 21_06_57-Call of Duty®_ Modern Warfare® Remastered Multiplayer](https://user-images.githubusercontent.com/113702897/209437686-4236b90a-903f-4f4e-97c2-69cfaefadea6.png)
![2022-12-24 21_07_27-Call of Duty®_ Modern Warfare® Remastered Multiplayer](https://user-images.githubusercontent.com/113702897/209437688-731fea04-5292-4eba-94b2-ad76db15942a.png)
![2022-12-24 21_07_37-Call of Duty®_ Modern Warfare® Remastered Multiplayer](https://user-images.githubusercontent.com/113702897/209437689-f036cdda-7190-4b8d-a966-442a4388e36d.png)

**Comment by mjkzy** [comment]
figured it out finally after unfortunately 2 hours of reversing that made me realize it's not the game, it's our issue :')

it's because of a patch we implemented not long ago that prevents the server from modifying the fov 
![image](https://user-images.githubusercontent.com/64374267/209466817-1eedc6b4-1f92-44c1-921c-1dd5e23395c3.png)

**Comment by amrurikaj** [comment]
oh man 😂.do you think in future this thing can be fixed or because of this patch,nothing can be done?
