### ISSUE TITLE
activity problem in some servers

### ISSUE THREAD

**Issue by hos80en** [h1-mod/h1-mod#390]
In "HGM" servers when i arrived i can play for a few minutes with a extreme lag but after it everything get stoped in game, i can shoot or walk and time is passing but characters dosnt show any reaction, they don't move and just stagnate similar when internet connection lost but my connection is alive. I haven't this problem on other servers. Please show me a solution this servers is only one which real guys play in and it has good ping for me. Sorry for my bad english

**Comment by mjkzy** [comment]
please record a video showing what is happening. the extreme lag you are experiencing might be the shader caching loading the map for the first time.
