### ISSUE TITLE
WHERE IS THE PLAYERS 2 FOLDER AND IF SO I CAN'T LAUNCH IT WITHOUT IT

### ISSUE THREAD

**Issue by TXExpliz** [h1-mod/h1-mod#399]
I downloaded the latest h1-mod_full_files but i do not see the "players2" folder ANY WHERE. AND IT STILL DOESN'T LET ME PLAY WITHOUT. so can anyone help me with this problem?

**Comment by VladWinner** [comment]
https://docs.h1.gg/errors
