### ISSUE TITLE
Playermodel got distorted while playing with bots in private match

### ISSUE THREAD

**Issue by cassualter226** [h1-mod/h1-mod#453]
I was playing TDM with bots, then found sometimes playermodels might be disroted, soldiers were wield their guns in a ridiculous posture......
![h1-mod 2023-01-08 20-04-37-64](https://user-images.githubusercontent.com/106251070/211195406-bcc95e1a-7150-4fa1-8ba9-9b308866fa8b.jpg)
It usually happens after 2 or 3 rounds of private matches with bots. As the issue comes out, the USMC rifleman in the lobby menu stands like this, also.
![h1-mod 2023-01-08 19-37-40-38](https://user-images.githubusercontent.com/106251070/211195942-7e2b2db9-7314-4bff-b77c-3d6fd6496e03.jpg)
![h1-mod 2023-01-08 18-06-23-82](https://user-images.githubusercontent.com/106251070/211195954-ed115449-4cb2-4858-8403-2acbee7f717f.jpg)
I've asked for a temporary solution of it, input vid_restart in console, nothing happened but just made the menu background into a darkness as I did that, then made the start game botton in the menu unselectable. As I managed to forced start the game with xpartygo, I found those playermodels still wield the guns in that way......
Now I need an exact temporary solution before the issue got wiped out, maybe if there's something I should do after input vid_restart command?

**Comment by mjkzy** [comment]
fixed for now by taking the weapons patch out

**Comment by Mike-Reddick** [comment]
First, thanks for this mod, and congratulations, keep it please. I'm using the last H1 2.0.0 and I have the same issue with weapons, how to fix it?

**Comment by Mike-Reddick** [comment]
> fixed for now by taking the weapons patch out

How I do?

**Comment by mjkzy** [comment]
use latest h1-mod on main branch and this won't be a problem
