### ISSUE TITLE
can't use 3dmigoto

### ISSUE THREAD

**Issue by Crugnok** [h1-mod/h1-mod#461]
i use 3dmigoto on most of the cod games to disable things like blur, bloody screen etc but it won't get picked up by h1-mod.

i tried playing the wrapper in the bin folder where the two game exe's get placed but won't load from there either.

regular game exe's pick up the d3d11.dll just fine.

any chance of supporting wrappers like 3dmigoto?

the wrapper also needs to load nvapi64.dll.

**Comment by mjkzy** [comment]
probably not but if you get it to work, we'd be maybe interested in supporting

**Comment by Crugnok** [comment]
got it working with https://github.com/hasherezade/dll_injector

injected d3d11.dll with batch file and now it works.
