### ISSUE TITLE
[Github Workflow] Package precompiled zone files on build/deploy

### ISSUE THREAD

**Issue by WantedDV** [h1-mod/h1-mod#477]
Might I request for the "Release data artifacts" of Github Actions to contain the precompiled zone ff files rather than source code (zone_source, zonetool)? Preferably with the same file structure as used by the client.

**Comment by mjkzy** [comment]
we may consider this but for now, we're not gonna do. only one person controls the artifacts and such, so they need to set it up when they have time.
