### ISSUE TITLE
Binary was mapped at 0x7FF766CE000 (instead of 0x140000000) Something is severely broken :(

### ISSUE THREAD

**Issue by MakeshiftH2** [h1-mod/h1-mod#49]
![Screenshot 2022-04-22 050247](https://user-images.githubusercontent.com/39418044/164710618-da3a202c-5d32-458b-ad46-f4cd120b3f52.png)

**Comment by MakeshiftH2** [comment]
Whenever current develop branch is cloned and compiled, this error pops ups when launching either multiplayer or campaign.

**Comment by Martos** [comment]
This accoured on me when I try to load the latest version (1.15) of the game. Tried again with the first version (1.04) of the game resolve the issue

**Comment by MakeshiftH2** [comment]
> This accoured on me when I try to load the latest version (1.15) of the game. Tried again with the first version (1.04) of the game resolve the issue

Realized this was the issue. Thanks for clarifying.
