### ISSUE TITLE
Depot Credits don't accumulate in certain game modes

### ISSUE THREAD

**Issue by BoxOfMysteriez** [h1-mod/h1-mod#490]
Pretty self-explanatory, there seems to be an issue with the custom depot system where credits are not earned in specific game modes no matter what. Including when you even wait for map to transition to the next map. The affected game modes seem to be:

Domination
Sabotage
Headquarters
Hardpoint

**Comment by BoxOfMysteriez** [comment]
[scoreboard_override.zip](https://github.com/h1-mod/h1-mod/files/10611755/scoreboard_override.zip)

Update: I've found a potential fix for this issue by simply adding the affected game modes to the H1 scoreboard_override.lua on line 31. I'm not sure if this is the proper way to fix it or it was just an oversight

**Comment by mjkzy** [comment]
pushing fix later
