### ISSUE TITLE
Inconsistencies with certain commands

### ISSUE THREAD

**Issue by BoxOfMysteriez** [h1-mod/h1-mod#495]
r_PreloadShaders does not save on exit in multiplayer and will default back to 0 upon launch
com_maxFps does not save on exit in single player and will default back to 0 upon launch

**Comment by VladWinner** [comment]
> com_maxFps does not save on exit in single player and will default back to 0 upon launch

Fixed in https://github.com/h1-mod/h1-mod/pull/431. Install develop build.
