### ISSUE TITLE
Lui Error: Element has duplicate id

### ISSUE THREAD

**Issue by WantedDV** [h1-mod/h1-mod#515]
## Problem

`Lui Error: Element has duplicate id`

These lua script errors seem to lead to game instability and missing or broken ui elements (such as the in-game team change button). While these errors do not show any immediate problems in the game, they can cause fatal errors which appear most commonly: at the end of a match, when reloading lua, or when running `map_restart` or `fast_restart`. 

![scoreboard_override](https://user-images.githubusercontent.com/122710241/221076652-e81f9d26-aeaf-4f91-8740-fbf2e3174b02.PNG)

## Cause

From my understanding it happens when we try to add or overwrite an element that already exists. As for `scoreboard_override.lua` we create a local copy of the original scoreboard, modify the copy, and finally overwrite the global original. Maybe we just need to remove the the global from the registered elements before overwriting? 

## Resolution

Everything we need looks to be in `ui/lui/luielement` including the function that throws the duplicate header message, and helper functions to add and remove elements.

## Things I have tried

I tried to redefine some functions in luielement to handle these duplicate headers but I am having trouble overriding that file.

## Additional Info

- The easiest way to reproduce these errors is to use `xblive_privatematch 0;map_restart` in the console.
- IF no duplicate id error is thrown, then this command works fine and enables ranking in a private match.

- There is another duplicate id in `common.lua` which is embedded in the h1-mod.exe

![lui_common](https://user-images.githubusercontent.com/122710241/221076658-b131b216-70d9-4ef4-a95f-c8a5ce060e9b.PNG)

**Comment by fedddddd** [comment]
Ranking only works with force_ranking 1, without it no team is assigned to the player which will cause that error

**Comment by fedddddd** [comment]
Its a dvar, just execute `set force_ranking 1`
