### ISSUE TITLE
MISSING file

### ISSUE THREAD

**Issue by Polito1** [h1-mod/h1-mod#56]
where can i find the first version (1.04) of the game ? i have the game on steam already

**Comment by skkuull** [comment]
You can use this https://github.com/SteamRE/DepotDownloader or watch this yt video it'll explain how to get them "requires ownership of original mwr on steam" https://www.youtube.com/watch?v=LeB0JwfO2us

**Comment by Polito1** [comment]
should i install the shaders ? because its stuck at 0%

**Comment by Reddoorcoldwar** [comment]
Just hit cancel. it won't preload.  Also do /disable_shader_caching 1
