### ISSUE TITLE
Is there a way to have more maps ? like dlc ones

### ISSUE THREAD

**Issue by Polito1** [h1-mod/h1-mod#57]
Also, sorry for creating Issues, if somebody can send a discord or a way for me to talk with devs, this would be great :)

**Comment by skkuull** [comment]
There is a list of maps that you can add them from 1.15 to 1.04:
mp_carentan
mp_showdown
mp_strike
mp_broadcast
mp_creek
mp_cargoship

Discord isn't public for the moment

**Comment by Polito1** [comment]
how can i import them into my h1 installation ? i tried for showdown but i get an error when /map mp_showdown

**Comment by skkuull** [comment]
you still need to have the imagefiles are required for them in the root folder of h1, I can list them as well
imagefile50, imagefile55, imagefile56, imagefile57, imagefile59, imagefile90, imagefile91

**Comment by Polito1** [comment]
got the disk read error when lauching a map now

**Comment by skkuull** [comment]
> got the disk read error when lauching a map now

clearly you're doing something wrong

**Comment by Polito1** [comment]
for exemple, i moved all the .ff of strike in the game files, and the eng_ one in the english folder.
after i added the imagefile and when i launch, it loads and then crashes to disk reading error.

**Comment by skkuull** [comment]
> 

if the error was `disk error` then the problem is from the imagefiles
