### ISSUE TITLE
Couldn't use aim assist

### ISSUE THREAD

**Issue by Li-goudan** [h1-mod/h1-mod#572]
Configuration: Laptop, win10, xbox one s controllers.
Description: The campaign mode has aim assist, but there is no aim assist in the multiplayer game, and I don’t know where to open it.

BTW,  it's really a wonderful project. Thanks for your contribution.

**Comment by VladWinner** [comment]
`aimassist_enabled` command (enabled by default)

**Comment by Li-goudan** [comment]
> `aimassist_enabled` command (enabled by default)

It‘s weird that the command line shows that the `aimassist_enabled` is 1, which I think means that the aim assist is turned on, but it still does not work in multiplayer.
