### ISSUE TITLE
How do I build?

### ISSUE THREAD

**Issue by ItsJokerZz** [h1-mod/h1-mod#58]
I've git cloned it into a folder, opened it VS2022 and tried to build, but got a bunch of dependencies build errors.
How can I build, or downloaded a prebuilt one?
![Screenshot_19](https://user-images.githubusercontent.com/47442947/168495407-046690a3-4e63-4d1e-ae7e-7c5b2030c081.png)
![Screenshot_20](https://user-images.githubusercontent.com/47442947/168495408-bfaaeb52-6696-4ab1-973e-19b9d53e6206.png)
There's no discord, and the site download legit doesn't work.

**Comment by DoktorSAS** [comment]
Have you run the generate.bat?
If no do it
