### ISSUE TITLE
Can't get H1 to work on Linux

### ISSUE THREAD

**Issue by papamikey** [h1-mod/h1-mod#595]
Hi, I've been trying to play since the update that added wine support. I just haven't said anything cause at the time I never cared that much, but now that I've heard our good friends at SM2 are switching to the engine, I thought I'd give it a try. It never seemed to launch no matter what launcher I used, no matter what proton version, or anything. Do I have to use the Steam version of the game for it to work on Linux? Or am I doing something wrong? I would love help.

Whenever I launch the game, the launcher is blank white. If I launch it through proton it's not white, but it doesn't have any options. If I use the args -singleplayer or -multiplayer it gets to the loading black screen with "h1-mod" at the corner and the animated mw logo in the other corner, and after 10 seconds it just closes.

**Comment by ViewAfterReview** [comment]
I got it to "work" by adding it as non-steam game with Launch Options: "-nosteam -multiplayer" and GE-Proton7-55. It mostly works but I can't cached the shaders and the movement is a bit choppy. I am still investigating.

**Comment by papamikey** [comment]
> I got it to "work" by adding it as non-steam game with Launch Options: "-nosteam -multiplayer" and GE-Proton7-55. It mostly works but I can't cached the shaders and the movement is a bit choppy. I am still investigating.

Thank you, -nosteam worked. Cheers!
