### ISSUE TITLE
Download is unavailable

### ISSUE THREAD

**Issue by V3nilla** [h1-mod/h1-mod#60]
Hello Developers! I have problem with downloading h1-mod 1.4 on your website, when i'm clicking on Download button, nothing happened and i'm getting error on the website, it says - The waiting time for a response from the site has been exceeded docs.h1p.co(Maybe wrong translation, because translated from russian). How i can download latest available client build?

**Comment by skkuull** [comment]
First of all its not released yet, and if you want to play the client you need to build it your self (there is a guide to it in readme), Docs is wip.

**Comment by V3nilla** [comment]
> First of all its not released yet, and if you want to play the client you need to wait till it released or you build it your self (there is a guide to it in readme), Docs is wip.

Oh, thank you.
