### ISSUE TITLE
runner.exe does nothing

### ISSUE THREAD

**Issue by MattKlay** [h1-mod/h1-mod#61]
I built the solution (and run generate.bat before) but It does litterally nothing. I tried to put the exe in MWR's folder but it didn't work either.

**Comment by skkuull** [comment]
How about you read readme? and you should launch the game thru H1-Mod.exe

**Comment by MattKlay** [comment]
I follow the readme step by step, h1-mod.exe not exist anymore

**Comment by Reddoorcoldwar** [comment]
Go to "Actions"
Select latest commit on top.
Scroll down to Artifacts and Release binaries/

**Comment by MattKlay** [comment]
Yes the links work perfectly !
Now I have to find the 1.04 Version of the game
