### ISSUE TITLE
Dedicated server files torrent not working

### ISSUE THREAD

**Issue by TastyTaco** [h1-mod/h1-mod#616]
Hey it seems no one is seeding the dedicated server full torrent, is there any other way to acquire those files?

**Comment by ZNicksonZ343** [comment]
Also, server.bat it doesn't send the heartbeat

**Comment by khabib227** [comment]
No, the H1 mod is completely dead, the developers don't want keep and support it anymore, was just a lost of time to devs and to us. H1 don't deserve even our attention. But has other Call of Duty mods that you can download the full game easily and has good support go to it. H1 is dead, the developers can archive the project soon.

**Comment by skkuull** [comment]
Nobody cares ab ur opinion lil bro

**Comment by ZNicksonZ343** [comment]
> No, the H1 mod is completely dead, the developers don't want keep and support it anymore, was just a lost of time to devs and to us. H1 don't deserve even our attention. But has other Call of Duty mods that you can download the full game easily and has good support, try the other mods. H1 is dead, the developers can archive the project soon.

Just shut up man, this project is great and still completely useful. Of course it deserves our attention
