### ISSUE TITLE
No Audio on Steam Deck

### ISSUE THREAD

**Issue by mersiusvds** [h1-mod/h1-mod#617]
I managed to get H1-Mod to work through Steam on the Steam Deck using both the official Proton 8 and GE-Proton 8.3. The game runs perfect and the shaders compile yet no matter what I try there is absolutely no audio. I've tried the built in speakers and Bluetooth headphones but nothing. I've tried running it in gamemode and desktop mode and neither has audio. I also couldn't get it to open using lutris.

Edit missing info:
I'm using -nosteam -multiplayer to launch the game through Steam.

**Comment by mersiusvds** [comment]
Found the issue. The Steam Deck muted H1-Mod for some reason. Launching the game in desktop mode then alt-tabbing to the audio system settings and ummuting everything related to H1-Mod fixed it.

**Comment by mersiusvds** [comment]
Found the issue. The Steam Deck muted H1-Mod for some reason. Launching the game in desktop mode then alt-tabbing to the audio system settings and ummuting everything related to H1-Mod fixed it.

**Comment by joeyidc** [comment]
Hey little late here but I just got the .exe to load with the launch option, but I’m getting no option to select multiplayer or single player when it loads, just the h1 screen, may I ask how you got through this?
