### ISSUE TITLE
H1-Mod crashing the game.

### ISSUE THREAD

**Issue by V3nilla** [h1-mod/h1-mod#63]
So, i got 1.4 .exe and my game is started and instantly crashed.
Minidump
[h1-mod-crash-2-2022-05-17-10-31-59.zip](https://github.com/h1-mod/h1-mod/files/8705790/h1-mod-crash-2-2022-05-17-10-31-59.zip)

**Comment by mjkzy** [comment]
crashes in DB_LinkXAssetEntry1, which is when the game is loading stuff from fastfiles I think. you may have corrupted game files.
