### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by MattKlay** [h1-mod/h1-mod#64]
When I try to launch the game with the client, I get this message :
---------------------------
Memory error
---------------------------
Memory error. Your hard drive is probably running out of free space. (12)
---------------------------
OK   
---------------------------

Also there is the state of the console :
Loading fastfile eng_code_pre_gfx_mp
Loading fastfile code_pre_gfx_mp
Loading fastfile eng_patch_code_pre_gfx_mp
Loading fastfile eng_cache_code_pre_gfx_mp
Loading fastfile patch_code_pre_gfx_mp
Loading fastfile cache_code_pre_gfx_mp

**Comment by mjkzy** [comment]
try starting the game with the launch paramater `-memoryfix`.
