### ISSUE TITLE
Multiplayer files and parameters

### ISSUE THREAD

**Issue by khabib227** [h1-mod/h1-mod#657]
@mjkzy sorry, but just one more question, please, I want to use the "h1_dedicated_server_full" to make a dedicated server and also I want to use it as a multiplayer only client in an another PC, you explained in other issue that the dedicated server is all the same files of the full version without imagefiles/soundfiles. I just want to ask you if I want to use the dedicated server pack also as a mp only client I need all soundfiles.pak and all imagefiles.pak without any exception? I know you don't want to talk about it here, but I know you understand about MWR a lot, and I'm just interested in dedicated server and in a multiplayer only client to use less storage space. What files exactly I need from full version to do a mp only client? And I know that h1_mod.exe support some parameters like -singleplayer or -multiplayer, where I get all supported parameters? Thanks.

**Comment by mjkzy** [comment]
to do a MP only client, you would remove everything that doesn't have a mp_ prefix. don't go mindlessly removing everything though. exceptions are common, patches, etc.

**Comment by khabib227** [comment]
And I need all files with .pak extension also sure?
