### ISSUE TITLE
(BUG) Shift + Tab don't work in console

### ISSUE THREAD

**Issue by Mike-Reddick** [h1-mod/h1-mod#661]
When you write something in console, that has a lot of results you need use Shift + Tab to show all results, to see all commands with the word you wrote, here this shortcut don't work. I'm using last version of Win 10.

**Comment by khabib227** [comment]
@fedddddd  I'm with the same problem here, without this feature how I can see the available commands? Isn't planned that the console work well? Is planned that this bug still not fixed is it?
