### ISSUE TITLE
Unlock all game modes

### ISSUE THREAD

**Issue by khabib227** [h1-mod/h1-mod#664]
Please add option to unlock all game modes as Capture the Flag, Prop Hunt, Demolition etc, and all Classes Custom Slots, more than 5, in private match.

**Comment by khabib227** [comment]
Thanks for this mod and sorry something I said before, I understand the issue with copyrights, your are right!

**Comment by eliottmusk** [comment]
Capture the flag is available, just update H1-Mod, Prop and Demolition not yet.
