### ISSUE TITLE
Feature Request: Add functionality to use the Private Match Game Lobby UI.

### ISSUE THREAD

**Issue by henronmegatron** [h1-mod/h1-mod#717]
I would like the addition of the Game Lobby UI to be available for locally hosted MWR matches, as this would prevent the need for each user to type the "connect" command whenever a match rotates.

A screenshot of the UI that I am referencing is shown below.

![2024-01-07_22-25-45](https://github.com/h1-mod/h1-mod/assets/151472770/463e8464-53fa-41ad-bc48-a3e51bd2ff33)

**Comment by mjkzy** [comment]
we don't emulate the lobby system, so it's just not possible atm. :')
