### ISSUE TITLE
The game doesn't start up anymore

### ISSUE THREAD

**Issue by ThisIsSpy** [h1-mod/h1-mod#725]
I have installed h1 mod yesterday, played for quite a bit and then went to sleep. Today, however, if I try to play the game using the h1 exe, it doesn't start up anymore. It doesn't give me any error message or shows me a splash screen, just an error sound and that's all. Task Manager shows that the h1 mod does start for half a second but then it quits. I have reinstalled both the h1 mod and the game and it still doesn't work. I have no antivirus except the Windows Defender and it doesn't block the exe or any files associated with it (at least it doesn't tell me that). Does anyone know how could I fix this?

**Comment by ThisIsSpy** [comment]
Forgot to add, but the game runs fine if I start it from Steam and I only have the multiplayer component installed

**Comment by mjkzy** [comment]
do you have any crashdumps that are produced?

**Comment by ThisIsSpy** [comment]
> do you have any crashdumps that are produced?

I don't see any in the game folder. They should be located there, right?

**Comment by mjkzy** [comment]
it’ll be in <mwr folder>/crashdumps/

**Comment by ThisIsSpy** [comment]
> it’ll be in <mwr folder>/crashdumps/

Strange, I don't have such folder and I don't think I have ever seen it in the mwr folder

**Comment by mjkzy** [comment]
sorry, `%mwr folder%/minidumps/`

**Comment by ThisIsSpy** [comment]
> sorry, `%mwr folder%/minidumps/`

Don't have that one either but after some digging around the AppData folders, I found a few crashdumps from h1 mod that are dated 11th of January. That is before the h1 stopped working completly but it did refuse to boot up a few times before it completly stopped working so it might be of help but most probably no. Not sure if opening them through VS is the right way but that's how my PC decided to open them

![image](https://github.com/h1-mod/h1-mod/assets/105442509/92fa077a-efa3-45a5-bbe9-3bc14430b60b)

All the crashdumps have the same error btw

**Comment by mjkzy** [comment]
if you can join the Discord, i can try to help you debug it

**Comment by mjkzy** [comment]
closing as this is stale. if you need help, join the Discord and @ me (my discord user is mjkzy)
