### ISSUE TITLE
Add a linux version of the launcher

### ISSUE THREAD

**Issue by ajlittle** [h1-mod/h1-mod#88]
Currently, running the launcher through Fedora Linux gives this screen.

![image](https://user-images.githubusercontent.com/1747872/175580779-42dfb461-56f7-4744-8973-987d5f384d46.png)

Including a launcher or an alternative to allow users to install through Linux would be great, I'd willing to test out any builds that are pushed for this too.

**Comment by skkuull** [comment]
launch h1-mod.exe with -mulitplayer or -singleplayer arguments

**Comment by ajlittle** [comment]
Launching with both -multiplayer and -singleplayer results in a black screen popup. It did create the h1-mod folder in the files though.

**Comment by ajlittle** [comment]
After a few minutes of leaving it open, it throws the error: Unsupported Call of Duty: Modern Warfare Remastered version (1.15).
Using a genuine copy through steam

**Comment by papamikey** [comment]
+1

**Comment by skkuull** [comment]
> +1

the team is collecting information about it

**Comment by fedddddd** [comment]
The issue is that the steam check or some other check done by arxan fails on linux so the game just goes into a sleep loop

**Comment by papamikey** [comment]
![Screenshot_20220624_192101](https://user-images.githubusercontent.com/97386118/175733404-47b9a95d-7a2f-46a8-9c27-cc68e24a45a0.png)

**Comment by pukmajster** [comment]
Same issue here on Fedora, would love to play.

**Comment by mjkzy** [comment]
we may look into this but as fed said, a sleep loop is happening and this is a issue with the game's DRM. low priority for now, sorry boys

**Comment by DeZ7ro** [comment]
Same issue on pop os, ill experiment a bit and see if i can make it work

**Comment by mjkzy** [comment]
just because it works for you doesn't mean it works for everyone.

> Same issue on pop os, ill experiment a bit and see if i can make it work. Sadly i couldnt get anywhere, i tried launching the .exe as a non steam game but got the same result. Maybe someone who knows how X labs and plutonium were made compatible can help out?

the DRM protection is strogn compared to IW6x/S1x. we probably have a patch here that does something that Arxan doesn't like on Linux
