### ISSUE TITLE
crashing in menus 

### ISSUE THREAD

**Issue by SictionArc** [h1-mod/h1-mod#89]
[h1-mod-crash-2-2022-06-24-13-07-58.zip](https://github.com/h1-mod/h1-mod/files/8978701/h1-mod-crash-2-2022-06-24-13-07-58.zip)
![image](https://user-images.githubusercontent.com/108090245/175609444-4b6b326e-43e4-4a78-a51f-d7f4171d777d.png)
appears to be crashing when i refresh the browser which is funny

**Comment by fedddddd** [comment]
Add me on discord fed#0001

**Comment by SictionArc** [comment]
"not accepting friend requests" just add me SictionArc#6597
