### ISSUE TITLE
Cant get rid of the "Out of memory" error

### ISSUE THREAD

**Issue by BigMommaYeech** [h1-mod/h1-mod#94]
I´ve tried: Uninstalling Avast antivirus, disabling shader cache, updating drivers, creating player2 folder, editing player2 config, and I have enough ram and ssd space for it. I don´t understand what I´m missing. I´m using the steam version.

**Comment by efinst0rm** [comment]
Have you checked out this https://docs.h1.gg/troubleshoot/#memory-error-crash ?

**Comment by mjkzy** [comment]
just to clarify, it should be `players2`, not `player2`. also, using the `-memoryfix` parameter should generate it automatically

**Comment by BigMommaYeech** [comment]
I did it, thanks yall. this helped https://docs.h1.gg/troubleshoot/#memory-error-crash. Seems like I was missing either DirectX or visual studio updates.
