### ISSUE TITLE
The server list does not have any servers

### ISSUE THREAD

**Issue by liveskai** [h1-mod/h1-mod#95]
**I don't see any servers**
![54e97434db91e6a4c5d5e46b1a733b06_unknown_width=1087 height=610](https://user-images.githubusercontent.com/54350655/175760094-b91d3118-6409-460d-a653-343a233b5f0f.png)

**Comment by pootylol** [comment]
I'm having the same issue, any known workaround or fix?

**Comment by Ritorikal** [comment]
ok, i thought i was insane, same here with no servers. wonder whats up.

**Comment by InSovietCS** [comment]
Master is down. Check the discord pins for manual server connects and their IPs in #general. Visit the VC to ask which ones are populated ;)

**Comment by Ritorikal** [comment]
gotcha, thx!!!
